<?php

/**
 * Returns the import map for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "preload" set to true for any modules that are loaded on the initial
 *     page load to help the browser download them earlier.
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => 'app.js',
        'preload' => true,
    ],
    '@symfony/stimulus-bundle' => [
        'path' => '@symfony/stimulus-bundle/loader.js',
    ],
    '@hotwired/stimulus' => [
        'downloaded_to' => 'vendor/@hotwired/stimulus.js',
        'url' => 'https://cdn.jsdelivr.net/npm/@hotwired/stimulus@3.2.2/+esm',
    ],
    'typed.js' => [
        'downloaded_to' => 'vendor/typed.js.js',
        'url' => 'https://cdn.jsdelivr.net/npm/typed.js@2.1.0/+esm',
    ],
    '@simplewebauthn/browser' => [
        'downloaded_to' => 'vendor/@simplewebauthn/browser.js',
        'url' => 'https://cdn.jsdelivr.net/npm/@simplewebauthn/browser@8.3.4/+esm',
    ],
];
