<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => 'app.js',
        'entrypoint' => true,
    ],
    '@symfony/stimulus-bundle' => [
        'path' => '@symfony/stimulus-bundle/loader.js',
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.2',
    ],
    'typed.js' => [
        'version' => '2.1.0',
    ],
    '@simplewebauthn/browser' => [
        'version' => '8.3.4',
    ],
    '@fontsource-variable/inter' => [
        'version' => '5.0.15',
    ],
    '@fontsource-variable/inter/index.min.css' => [
        'version' => '5.0.15',
        'type' => 'css',
    ],
    'material-icons' => [
        'version' => '1.13.12',
    ],
    'material-icons/iconfont/material-icons.min.css' => [
        'version' => '1.13.12',
        'type' => 'css',
    ],
];
